spring:
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST:localhost}
        port: ${QDRANT_PORT:6333}
        collection-name: materials
        distance-type: Cosine
cors:
  allowed-origins: http://localhost:5173,http://127.0.0.1:5173
server:
  port: 8080
app:
  material:
    upload-dir: ${MATERIAL_UPLOAD_DIR:./data/materials}
